### PR TITLE
Fix build errors (GCC 10, Debian Bullseye)

### PR DESCRIPTION
**Pull request by rpaciorek**
* add missing header
* fabsf is part of C++17, not C++11
* fix order const typename
* update/fix SWIG
* OpenGL build "SWIG OpenGL" only when OpenGL is available

### CODE REVIEW

**Comment by Ident** [comment]
@rpaciorek  fabs is part of C++11, look here https://en.cppreference.com/w/cpp/numeric/math/fabs 
`float       fabsf( float arg );
	(since C++11)`

**Comment by rpaciorek** [comment]
> @rpaciorek fabs is part of C++11, look here https://en.cppreference.com/w/cpp/numeric/math/fabs `float fabsf( float arg ); (since C++11)`

Probably you are right, but:
* opinions vary ;-) see https://stackoverflow.com/questions/54027717/is-fabsf-part-of-the-std-namespace-in-c11
* std::fabsf break build on clang (11.0.1-2) and gcc (10.2.1-6)
    * `error: ‘fabsf’ is not a member of ‘std’; did you mean ‘fabs’?`
    * https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79700

**Comment by Ident** [comment]
Good point, i will merge it then, thanks

**Comment by Ident** [comment]
Btw there is a lot of pointless formatting changes in ur commit like spaces/tabs at the end of things - preferrably do not do this because it pollutes the change history and makes it harder to track what went on on a line. I assume your IDE did autoformatting here. While this is fine for any code you write or edit, changing entire files like this becomes messy for history and reviews, even if technically your change is the right thing .

**Comment by rpaciorek** [comment]
Yes, my editor remove spaces at the end of lines. I can fix this and create new PR (`git diff -b` your friend :) ).
